stages:
  train:
    cmd: uv run python main.py
    deps:
      - src/
      - content/dataset
      - params.yaml
    params:
      - data
      - model
      - training
    outs:
      - models/model.keras